# SuperAI 构建配置
# 用于管理基础镜像和优化构建流程

version: '3.8'

services:
  # 基础镜像构建
  superai-base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: superai-base:latest
    
  # 核心服务构建（基于基础镜像）
  agent-planner-build:
    build:
      context: .
      dockerfile: microservices/agent-planner/Dockerfile.agi
    image: superai-agent-planner:latest
    depends_on:
      - superai-base
      
  agent-executor-build:
    build:
      context: .
      dockerfile: microservices/agent-executor/Dockerfile.agi
    image: superai-agent-executor:latest
    depends_on:
      - superai-base

# 构建命令示例：
# 1. 构建基础镜像：docker-compose -f docker-compose.build.yml build superai-base
# 2. 构建所有服务：docker-compose -f docker-compose.build.yml build
# 3. 构建特定服务：docker-compose -f docker-compose.build.yml build agent-planner-build